# Configuration file for Borealis: SU2_preCICE_OPT.py

# Specify if we need to initialize MPI
with_MPI: True

# Specify preCICE participant name
precice_name: "Fluid"

# Specify preCICE config file
precice_config: "../precice-config.xml"

# Specify the preCICE mesh name"
precice_mesh: "Fluid-Mesh"

# Dimension of optimizer domain (2D/3D): 2 or 3
nDim: 2

# Serquential optimization
in_sequential: False

# Moving boundary
MovingMarker: "interface"

# preCICE writing and reading variables
precice_read: "Displacement"
precice_write: "Force"

